version: "3"

services:
  migrate:
    build: migrate/
    depends_on:
      - database
    ports:
      - "3000:3000"
  database:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: fop
    ports:
      - "5432:5432"
